services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 4457:5432
    env_file:
      - ./back-end/.env
    volumes:
      - db:/var/lib/postgresql/data
  node_app:
    container_name: node_app
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - database
    env_file:
      - ./back-end/.env
  react_app:
    container_name: react_app
    build: ./front-end
    depends_on:
      - database
      - node_app
    volumes:
      - build_react:/var/www/html
  nginx_app:
    container_name: nginx_app
    build: ./nginx
    ports: 
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - database
      - node_app
      - react_app
volumes:
  db:
  build_react: