
services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 4457:5432
    env_file:
      - .env.test

  node_app:
    container_name: node_app
    build: .
    ports:
      - 5000:5000
    depends_on:
      - database
    env_file:
      - .env.test